spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example
    username: postgres
    password: password
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    drop-first: true
  jpa:
    hibernate:
      ddl-auto: validate

qr-code:
  width: 200
  height: 200

job:
  post-visibility:
    initial-delay: 0
    fixed-delay: 36000

api:
  public-service-url: localhost:8080
  version: v1