spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example
    username: postgres
    password: password
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    drop-first: true

qr-code:
  width: 200
  height: 200

api:
  public-service-url: localhost:8080
  version: v1

